<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => '激活',
    'Are you sure you want to delete this item?' => '你确定你要删除这项吗？',
    'Change at your own risk' => '更新可能会带来风险',
    'Create' => '创建',
    'Create {modelClass}' => '创建 {modelClass}',
    'CreatedAt' => '创建时间',
    'Delete' => '删除',
    'ID' => '',
    'Key' => '键',
    'UpdatedAt' => '更新时间',
    'Reset' => '重置',
    'Search' => '搜索',
    'Section' => '段',
    'Setting' => '设置',
    'Type' => '分类',
    'Update' => '更新',
    'Update {modelClass}: ' => '更新 {modelClass}: ',
    'Value' => '值',
];
